name: Family Tree CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          PG_USERNAME: ${{ secrets.PG_USERNAME }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: bitnami/redis:latest
        env:
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
        ports:
          - 6380:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.19'

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Run linter
      run: golangci-lint run

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    # - name: Build Docker image
    #   run: docker build -t family-tree-image .

    # - name: Run tests
    #   run: docker-compose run --rm family-tree-image go test ./...

    # - name: Build and push Docker image
    #   run: |
    #     docker build -t family-tree-image .
    #     docker tag family-tree-image ${{ secrets.DOCKER_REGISTRY }}/family-tree-image:latest
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push ${{ secrets.DOCKER_REGISTRY }}/family-tree-image:latest

    - name: Clean up
      run: |
        docker-compose down
        docker image rm -f family-tree-image
